server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/auth/**

        - id: content-service
          uri: http://localhost:8081
          predicates:
            - Path=/content/**
          filters:
            - StripPrefix=1

        - id: watch-history-service
          uri: http://localhost:8082
          predicates:
            - Path=/watch/**

        - id: recommendation-service
          uri: http://localhost:8083
          predicates:
            - Path=/recommendations/**

        - id: ai-recommendation-service
          uri: http://localhost:8090
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=1

        - id: content-admin
          uri: http://localhost:8081
          predicates:
            - Path=/admin/**
