server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb+srv://saimadhav204_db_user:5I6TPvndTlRgmAex@content-cluster.blxl7d0.mongodb.net/contentdb


tmdb:
  api-key: 66ee64af37934a734c7cc9989fea0964
  base-url: https://api.themoviedb.org/3
  image-base-url: https://image.tmdb.org/t/p/w500
